#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "[pre-commit] running eslint, prettier & unit tests in parallel"
prettier --write src > /dev/null & PID1=$!
npm run lint:fix > /dev/null & PID2=$!
npm test --silent & PID3=$!

CODE=0
wait $PID1 || CODE=$?
wait $PID2 || CODE=$?
if [[ "${CODE}" != "0" ]]; then
    echo 'ERROR: eslint failed'
    trap 'jobs -p | xargs kill' EXIT
    exit 1
fi

if [[ "${CODE}" == "0" ]]; then
    wait $PID3 
fi


